const latestProperties = [
  {
    id: 1,
    logo: "/images/LatestOne.svg",
    title: "Green Meadows",
    verified: "/images/verified-added.png",
    locationIcon: "location.png",
    location: "Shadnagar",
    price: "$25,000",
    size: "500 sq. yards",
    rating: "4.5",
  },
  {
    id: 2,
    logo: "/images/LatestOne.svg",
    title: "Sunny Acres",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Maheshwaram",
    price: "$30,000",
    size: "600 sq. yards",
    rating: "4.7",
  },
  {
    id: 3,
    logo: "/images/LatestOne.svg",
    title: "Sunny Acres",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Maheshwaram",
    price: "$30,000",
    size: "600 sq. yards",
    rating: "4.7",
  },
  {
    id: 4,
    logo: "/images/LatestOne.svg",
    title: "Green Meadows",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Shadnagar",
    price: "$25,000",
    size: "500 sq. yards",
    rating: "4.5",
  },
  {
    id: 5,
    logo: "/images/LatestOne.svg",
    title: "Sunny Acres",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Maheshwaram",
    price: "$30,000",
    size: "600 sq. yards",
    rating: "4.7",
  },
  {
    id: 6,
    logo: "/images/LatestOne.svg",
    title: "Sunny Acres",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Maheshwaram",
    price: "$30,000",
    size: "600 sq. yards",
    rating: "4.7",
  },
];

const recentProperties = [
  {
    id: 4,
    logo: "/images/LatestOne.svg",
    title: "Hillside Estates",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Bhongir",
    price: "$20,000",
    size: "400 sq. yards",
    rating: "4.3",
  },
  {
    id: 5,
    logo: "/images/LatestOne.svg",
    title: "Riverfront Lands",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Chevella",
    price: "$35,000",
    size: "700 sq. yards",
    rating: "4.8",
  },
  {
    id: 6,
    logo: "/images/LatestOne.svg",
    title: "Riverfront Lands",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Chevella",
    price: "$35,000",
    size: "700 sq. yards",
    rating: "4.8",
  },
  {
    id: 7,
    logo: "/images/LatestOne.svg",
    title: "Green Meadows",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Shadnagar",
    price: "$25,000",
    size: "500 sq. yards",
    rating: "4.5",
  },
  {
    id: 8,
    logo: "/images/LatestOne.svg",
    title: "Sunny Acres",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Maheshwaram",
    price: "$30,000",
    size: "600 sq. yards",
    rating: "4.7",
  },
  {
    id: 9,
    logo: "/images/LatestOne.svg",
    title: "Sunny Acres",
    verified: "verified.png",
    locationIcon: "location.png",
    location: "Maheshwaram",
    price: "$30,000",
    size: "600 sq. yards",
    rating: "4.7",
  },
];

export { latestProperties, recentProperties };
