const latestProperties = [
  {
    id: 1,
    logo: "/images/LatestOne.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 2,
    logo: "/images/LatestTwo.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 3,
    logo: "/images/LatestThree.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 4,
    logo: "/images/LatestOne.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 5,
    logo: "/images/LatestTwo.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 6,
    logo: "/images/LatestThree.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
];

const recentProperties = [
  {
    id: 1,
    logo: "/images/LatestOne.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 2,
    logo: "/images/LatestTwo.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 3,
    logo: "/images/LatestThree.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 4,
    logo: "/images/LatestOne.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 5,
    logo: "/images/LatestTwo.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
  {
    id: 6,
    logo: "/images/LatestThree.svg",
    title: "Janapriya Ventures",
    verified: "/images/verified-addedProfile.svg",
    locationIcon: "/images/location.svg",
    location: "Shamshabad, Hyderabad",
    price: "1.2 CR",
    size: "2200 sqft ",
    rating: "1200 per sqft",
  },
];

export { latestProperties, recentProperties };
